# Generated by Django 3.1.7 on 2022-05-08 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cel_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('represantativeNationalId', models.CharField(max_length=16)),
                ('father_fullName', models.CharField(max_length=100)),
                ('mother_fullName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=30)),
                ('cell', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('physical_disability', models.CharField(choices=[('NO', 'No'), ('Physical', 'Physical'), ('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Little', 'Little'), ('Albinos', 'Albinos'), ('Deaf-Blind', 'Deaf-Blind'), ('Multiple', 'Multiple')], default='NO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=30)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.province')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vil_name', models.CharField(max_length=30)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.cell')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherNationalId', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('Primary Level', 'Primary Level'), ('Diploma', 'Diploma'), ('Care Giver', 'Care Giver Certificate'), ('Diploma in Education', 'Diploma in Education'), ('Bachelor in Education', 'Bachelor in Education'), ('Masters in Education', 'Masters in Education'), ('PhD in Education', 'PhD in Education')], max_length=30)),
                ('recruit_year', models.IntegerField()),
                ('physical_disability', models.CharField(choices=[('NO', 'No'), ('Physical', 'Physical'), ('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Little', 'Little'), ('Albinos', 'Albinos'), ('Deaf-Blind', 'Deaf-Blind'), ('Multiple', 'Multiple')], default='NO', max_length=50)),
                ('service', models.CharField(choices=[('Teacher', 'Teacher'), ('Care giver', 'Care giver'), ('Nurse', 'Nurse'), ('Fusion', 'Fusion'), ('Supporting Staff', 'Support Staff')], max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('dob', models.DateField()),
                ('correspond_age', models.IntegerField()),
                ('year_reg', models.IntegerField()),
                ('physical_disability', models.CharField(choices=[('Autism', 'Autism'), ('Multiple', 'Multiple'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Cerebral Palsy ID', 'Cerebral Palsy ID'), ('Down syndrom', 'Down syndrom')], default='NO', max_length=50)),
                ('service_category', models.CharField(choices=[('SPECIAL EDUCATION', 'SPECIAL EDUCATION'), ('FUSION AND EDUCATION', 'FUSION AND EDUCATION')], max_length=50)),
                ('classe', models.CharField(choices=[('CLADE1', 'CLADE 1'), ('CLADE2', 'CLADE 2'), ('CLADE3', 'CLADE 3'), ('CLADE4', 'CLADE 4'), ('CLADE5', 'CLADE 5'), ('CLADE6', 'CLADE 6')], max_length=50)),
                ('familyNID', models.CharField(max_length=16)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('sectors', models.CharField(max_length=30)),
                ('cell', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('st_image', models.ImageField(blank=True, default='anonymous-user.png', null=True, upload_to='')),
                ('note', models.CharField(max_length=150)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.province')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.school')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffNationalId', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('Primary Level', 'Primary Level'), ('Diploma', 'Diploma'), ('Care Giver', 'Care Giver Certificate'), ('Diploma in Education', 'Diploma in Education'), ('Bachelor in Education', 'Bachelor in Education'), ('Masters in Education', 'Masters in Education'), ('PhD in Education', 'PhD in Education')], max_length=30)),
                ('recruit_year', models.IntegerField()),
                ('physical_disability', models.CharField(choices=[('NO', 'No'), ('Physical', 'Physical'), ('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Little', 'Little'), ('Albinos', 'Albinos'), ('Deaf-Blind', 'Deaf-Blind'), ('Multiple', 'Multiple')], default='NO', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect_name', models.CharField(max_length=30)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.district')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_amount', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('UNVERIFIED', 'UNVERIFIED'), ('VERIFIED', 'VERIFIED')], max_length=50, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.year')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.province'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school'),
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoordinatorNationalId', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('Primary Level', 'Primary Level'), ('Diploma', 'Diploma'), ('Care Giver', 'Care Giver Certificate'), ('Diploma in Education', 'Diploma in Education'), ('Bachelor in Education', 'Bachelor in Education'), ('Masters in Education', 'Masters in Education'), ('PhD in Education', 'PhD in Education')], max_length=30)),
                ('recruit_year', models.IntegerField()),
                ('physical_disability', models.CharField(choices=[('NO', 'No'), ('Physical', 'Physical'), ('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Little', 'Little'), ('Albinos', 'Albinos'), ('Deaf-Blind', 'Deaf-Blind'), ('Multiple', 'Multiple')], default='NO', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.school')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='sectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.sectors'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.CharField(max_length=9)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.year')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardNationalId', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('Primary Level', 'Primary Level'), ('Diploma', 'Diploma'), ('Care Giver', 'Care Giver Certificate'), ('Diploma in Education', 'Diploma in Education'), ('Bachelor in Education', 'Bachelor in Education'), ('Masters in Education', 'Masters in Education'), ('PhD in Education', 'PhD in Education')], max_length=30)),
                ('recruit_year', models.IntegerField()),
                ('physical_disability', models.CharField(choices=[('NO', 'No'), ('Physical', 'Physical'), ('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Little', 'Little'), ('Albinos', 'Albinos'), ('Deaf-Blind', 'Deaf-Blind'), ('Multiple', 'Multiple')], default='NO', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminNationalId', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('Primary Level', 'Primary Level'), ('Diploma', 'Diploma'), ('Care Giver', 'Care Giver Certificate'), ('Diploma in Education', 'Diploma in Education'), ('Bachelor in Education', 'Bachelor in Education'), ('Masters in Education', 'Masters in Education'), ('PhD in Education', 'PhD in Education')], max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
