# Generated by Django 3.1.7 on 2022-04-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Autism', 'Autism'), ('Multiple', 'Multiple'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Cerebral Palsy ID', 'Cerebral Palsy ID'), ('Down syndrom', 'Down syndrom')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Autism', 'Autism'), ('Multiple', 'Multiple'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Cerebral Palsy ID', 'Cerebral Palsy ID'), ('Down syndrom', 'Down syndrom')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='parent',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Autism', 'Autism'), ('Multiple', 'Multiple'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Cerebral Palsy ID', 'Cerebral Palsy ID'), ('Down syndrom', 'Down syndrom')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Autism', 'Autism'), ('Multiple', 'Multiple'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Cerebral Palsy ID', 'Cerebral Palsy ID'), ('Down syndrom', 'Down syndrom')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.CharField(choices=[('CLADE1', 'CLADE 1'), ('CLADE2', 'CLADE 2'), ('CLADE3', 'CLADE 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Autism', 'Autism'), ('Multiple', 'Multiple'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Cerebral Palsy ID', 'Cerebral Palsy ID'), ('Down syndrom', 'Down syndrom')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Autism', 'Autism'), ('Multiple', 'Multiple'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Cerebral Palsy ID', 'Cerebral Palsy ID'), ('Down syndrom', 'Down syndrom')], default='NO', max_length=50),
        ),
    ]
