# Generated by Django 4.1.1 on 2022-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='service_category',
            field=models.CharField(choices=[('SPECIAL EDUCATION', 'SPECIAL EDUCATION'), ('PHYSIO AND EDUCATION', 'PHYSIO AND EDUCATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='service',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Care giver', 'Care giver'), ('Nurse', 'Nurse'), ('Physio', 'Physio'), ('Supporting Staff', 'Support Staff')], max_length=50),
        ),
    ]
