# Generated by Django 3.1.7 on 2021-07-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='school',
        ),
    ]
