# Generated by Django 3.1.7 on 2022-04-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220410_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school'),
        ),
    ]
