# Generated by Django 3.1.7 on 2021-07-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_coordinator_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='sector',
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.province'),
            preserve_default=False,
        ),
    ]
