# Generated by Django 4.1.1 on 2022-12-16 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('student', '0002_alter_student_service_category_alter_teacher_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
