# Generated by Django 3.1.7 on 2022-04-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_coordinator_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='school',
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.course'),
        ),
    ]
