# Generated by Django 4.1.1 on 2022-12-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_coordinator_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='group',
        ),
    ]
