# Generated by Django 3.1.7 on 2022-04-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20220411_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AddField(
            model_name='teacher',
            name='service',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Care giver', 'Care giver'), ('Nurse', 'Nurse'), ('Fusion', 'Fusion'), ('Supporting Staff', 'Support Staff')], default='-----', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Physical', 'Physical'), ('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Little', 'Little'), ('Albinos', 'Albinos'), ('Deaf-Blind', 'Deaf-Blind'), ('Multiple', 'Multiple')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Physical', 'Physical'), ('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Little', 'Little'), ('Albinos', 'Albinos'), ('Deaf-Blind', 'Deaf-Blind'), ('Multiple', 'Multiple')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='parent',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Physical', 'Physical'), ('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Little', 'Little'), ('Albinos', 'Albinos'), ('Deaf-Blind', 'Deaf-Blind'), ('Multiple', 'Multiple')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Physical', 'Physical'), ('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Little', 'Little'), ('Albinos', 'Albinos'), ('Deaf-Blind', 'Deaf-Blind'), ('Multiple', 'Multiple')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.CharField(choices=[('CLADE1', 'CLADE 1'), ('CLADE2', 'CLADE 2'), ('CLADE3', 'CLADE 3'), ('CLADE4', 'CLADE 4'), ('CLADE5', 'CLADE 5'), ('CLADE6', 'CLADE 6')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='physical_disability',
            field=models.CharField(choices=[('Autism', 'Autism'), ('Multiple', 'Multiple'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Cerebral Palsy ID', 'Cerebral Palsy ID'), ('Down syndrom', 'Down syndrom')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='physical_disability',
            field=models.CharField(choices=[('NO', 'No'), ('Physical', 'Physical'), ('Blind', 'Blind'), ('Deaf', 'Deaf'), ('Little', 'Little'), ('Albinos', 'Albinos'), ('Deaf-Blind', 'Deaf-Blind'), ('Multiple', 'Multiple')], default='NO', max_length=50),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.CharField(max_length=8)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.year')),
            ],
        ),
    ]
