# Generated by Django 3.1.7 on 2022-04-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20220419_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='degree',
            field=models.CharField(choices=[('Primary Level', 'Primary Level'), ('Diploma', 'Diploma'), ('Care Giver', 'Care Giver Certificate'), ('Diploma in Education', 'Diploma in Education'), ('Bachelor in Education', 'Bachelor in Education'), ('Masters in Education', 'Masters in Education'), ('PhD in Education', 'PhD in Education')], max_length=30),
        ),
        migrations.AlterField(
            model_name='board',
            name='degree',
            field=models.CharField(choices=[('Primary Level', 'Primary Level'), ('Diploma', 'Diploma'), ('Care Giver', 'Care Giver Certificate'), ('Diploma in Education', 'Diploma in Education'), ('Bachelor in Education', 'Bachelor in Education'), ('Masters in Education', 'Masters in Education'), ('PhD in Education', 'PhD in Education')], max_length=30),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_amount',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='degree',
            field=models.CharField(choices=[('Primary Level', 'Primary Level'), ('Diploma', 'Diploma'), ('Care Giver', 'Care Giver Certificate'), ('Diploma in Education', 'Diploma in Education'), ('Bachelor in Education', 'Bachelor in Education'), ('Masters in Education', 'Masters in Education'), ('PhD in Education', 'PhD in Education')], max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='degree',
            field=models.CharField(choices=[('Primary Level', 'Primary Level'), ('Diploma', 'Diploma'), ('Care Giver', 'Care Giver Certificate'), ('Diploma in Education', 'Diploma in Education'), ('Bachelor in Education', 'Bachelor in Education'), ('Masters in Education', 'Masters in Education'), ('PhD in Education', 'PhD in Education')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('Primary Level', 'Primary Level'), ('Diploma', 'Diploma'), ('Care Giver', 'Care Giver Certificate'), ('Diploma in Education', 'Diploma in Education'), ('Bachelor in Education', 'Bachelor in Education'), ('Masters in Education', 'Masters in Education'), ('PhD in Education', 'PhD in Education')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='service',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Care giver', 'Care giver'), ('Nurse', 'Nurse'), ('Fusion', 'Fusion'), ('Supporting Staff', 'Support Staff')], max_length=50),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_name',
            field=models.CharField(max_length=4),
        ),
    ]
