# Generated by Django 3.1.2 on 2022-04-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_amount',
            field=models.IntegerField(),
        ),
    ]
